// -----------------------------------------------------------------------------
//    File: hook_nwnx.nss
//  System: Core Framework (event script)
//     URL: https://github.com/squattingmonk/nwn-core-framework
// Authors: Michael A. Sinclair (Squatting Monk) <squattingmonk@gmail.com>
// -----------------------------------------------------------------------------
// NWNX Events hook-in script. This script runs event queues for events
// generated by nwnx_events. It does not need to be placed in a slot.
// -----------------------------------------------------------------------------

#include "core_i_framework"
#include "nwnx_events"

void main()
{
    string sEvent = GetScriptParam(EVENT_NAME);
    if (sEvent != "")
        NWNX_Events_SubscribeEvent(sEvent, "hook_nwnx");
    else
        RunEvent(NWNX_Events_GetCurrentEvent());
}
